wip

diff --git a/puppet b/puppet
--- a/puppet
+++ b/puppet
@@ -1,5 +1,5 @@
 #!/usr/local/bin/cbsd
-#v11.0.0
+#v11.0.14
 MYARG="module jname"
 MYOPTARG="mode"
 MYDESC="Generate puppet manifests"
@@ -39,90 +39,12 @@ param=$( cbsdsql ${formfile} SELECT param FROM forms ORDER BY CAST\(order_id AS 
 load_forms
 load_new
 
-# todo
-# reload only when changed
 
-puppet_apply()
+apply_in_jail()
 {
-	local _jpuppet_dir
-	local _jpuppet_puppet_src
-	local _was_started
-
-	_jpuppet_dir="${jaildatadir}/${cbsd_helper_jname}-${jaildatapref}/usr/local"
-	_jpuppet_puppet_src="${_jpuppet_dir}/bin/puppet"
-
-	[ ! -x "${_jpuppet_puppet_src}" ] && err 1 "${MAGENTA}No such puppet in /usr/local/bin/puppet inside ${cbsd_helper_jname}${NORMAL}"
-
-	if [ ${jid} -eq 0 ]; then
-		jstart jname=${jname}
-		_was_started=0
-	else
-		_was_started=1
-	fi
-
-	[ $baserw -eq 1 ] && path="${data}"
-
-	[ -z "${path}" ] && err 1 "No path variable"
-
-	[ ! -d ${moduledir}/puppet.d/modules/public ] && err 1 "No such ${moduledir}/puppet.d/modules/public"
-	[ ! -d "${path}/usr/local/etc/puppet/modules" ] && mkdir -p ${path}/usr/local/etc/puppet/modules
-
-	[ ! -d ${path}/usr/local/etc/puppet ] && /bin/mkdir -p ${path}/usr/local/etc/puppet
-	[ ! -d ${path}/usr/local/etc/puppet/modules ] && /bin/mkdir ${path}/usr/local/etc/puppet/modules
-	/bin/cp -a ${moduledir}/puppet.d/hiera.yaml ${path}/usr/local/etc/puppet/hiera.yaml
-
-	# first - mount puppet jail source
-	[ ! -d "${path}/tmp/puppet" ] && mkdir -p ${path}/tmp/puppet
-	/sbin/mount -t nullfs -o ro ${_jpuppet_dir} ${path}/tmp/puppet
-	/sbin/mount -t nullfs -o ro ${moduledir}/puppet.d/modules/public ${path}/usr/local/etc/puppet/modules
-	/sbin/mount -t nullfs -o ro ${moduledir}/puppet.d ${path}/tmp/puppet/etc/puppet
-
-	[ $? -ne 0 ] && err 1 "Error mount ${moduledir}/puppet.d/puppet_root/modules to /usr/local/etc/puppet/modules inside jail"
-
-	[ ! -d ${path}/tmp/cbsd ] && /bin/mkdir -p ${path}/tmp/cbsd
-
-	generate_manifest > ${local_puppet_manifest_dir}/${module}.pp
-	/bin/cp -a ${local_puppet_manifest_dir}/${module}.pp ${path}/tmp/cbsd/${helpername}.pp
-
-	if [ -d /usr/local/etc/puppet/environments/production/manifests ]; then
-		echo "Copy manifest to /usr/local/etc/puppet/environments/production/manifests/${host_hostname}.pp"
-		echo "node \"${host_hostname}\" {" > /usr/local/etc/puppet/environments/production/manifests/${host_hostname}.pp
-#		/bin/cp ${local_puppet_manifest_dir}/${module}.pp /usr/local/etc/puppet/environments/production/manifests/${host_hostname}.pp
-		/bin/cat ${local_puppet_manifest_dir}/${module}.pp  >> /usr/local/etc/puppet/environments/production/manifests/${host_hostname}.pp
-
-		echo "}" >> /usr/local/etc/puppet/environments/production/manifests/${host_hostname}.pp
-
-	else
-		echo "no /usr/local/etc/puppet/environments/production/manifests, skip for coping manifest"
-	fi
-
-	generate_hieradata > ${local_puppet_hieradata_dir}/${module}.yaml
-	/bin/cp -a ${local_puppet_hieradata_dir}/${module}.yaml ${path}/tmp/cbsd/common.yaml
-
-	if [ -d /usr/local/etc/puppet/hieradata/production ]; then
-#		[ ! -d /usr/local/etc/puppet/hieradata/production/${helpername} ] && /bin/mkdir -p /usr/local/etc/puppet/hieradata/production/${helpername}
-		[ ! -d /usr/local/etc/puppet/hieradata/production/node ] && /bin/mkdir -p /usr/local/etc/puppet/hieradata/production/node
-		echo "Copy hiera to /usr/local/etc/puppet/hieradata/production/node/"
-		/bin/cp ${local_puppet_hieradata_dir}/${module}.yaml /usr/local/etc/puppet/hieradata/production/node/${host_hostname}.yaml
-	else
-		echo "no /usr/local/etc/puppet/hieradata/production, skip for coping hiera"
-	fi
-
-#	${ECHO} "${MAGENTA}Puppet in progress: ${GREEN}jexec for /tmp/cbsd/${helpername}.pp${NORMAL}"
-#	echo "jexec jname=${jname} /tmp/puppet/etc/puppet/puppetcbsd /tmp/cbsd/${helpername}.pp"
-
-#	jexec jname=${jname} /tmp/puppet/etc/puppet/puppetcbsd /tmp/cbsd/${helpername}.pp
-##	jexec jname=${jname} /usr/local/bin/puppet apply --hiera_config /usr/local/etc/puppet/hiera.yaml /tmp/cbsd/${helpername}.pp
-
-	if [ ! -x ${data}/usr/local/bin/puppet ]; then
-		jexec jname=${jname} env ASSUME_ALWAYS_YES=yes pkg install -y sysutils/puppet4
-	fi
-
-	certname=$( /usr/local/bin/puppet config print certname )
-
 	mkjhosts file=${data}/etc/hosts ips="${nodeip}" hosts="${certname}" template="Puppet-CBSD-module"
 
-	cat > ${data}/usr/local/etc/puppet/puppet.conf <<EOF
+	/bin/cat > ${data}/usr/local/etc/puppet/puppet.conf <<EOF
 [agent]
 server = ${certname}
 pluginsync = true
@@ -142,10 +64,9 @@ EOF
 		fi
 	fi
 
-	jexec jname=${jname} /usr/local/bin/puppet agent -t
+	jexec jname=${jname} env LANG=en_US.UTF-8 /usr/local/bin/puppet agent -t
 
 	echo "***"
-#	read p
 
 	/sbin/umount ${path}/usr/local/etc/puppet/modules
 	/sbin/umount ${path}/tmp/puppet/etc/puppet
@@ -156,6 +77,101 @@ EOF
 	else
 		[ -n "${have_restart}" ] && jexec jname=$jname ${have_restart}
 	fi
+}
+
+
+# todo
+# reload only when changed
+puppet_apply()
+{
+	local _jpuppet_dir
+	local _jpuppet_puppet_src
+	local _was_started
+
+	_jpuppet_dir="${jaildatadir}/${cbsd_helper_jname}-${jaildatapref}/usr/local"
+	_jpuppet_puppet_src="${_jpuppet_dir}/bin/puppet"
+
+	[ ! -x "${_jpuppet_puppet_src}" ] && err 1 "${MAGENTA}No such puppet in /usr/local/bin/puppet inside ${cbsd_helper_jname}${NORMAL}"
+
+	if [ ${jid} -eq 0 ]; then
+		case ${emulator} in
+			jail)
+				jstart jname=${jname}
+				_was_started=0
+				;;
+			*)
+				err 1 "${EMULATOR}VM is not running: ${GREEN}${jname}${NORMAL}"
+				;;
+		esac
+	else
+		_was_started=1
+	fi
+
+	[ ! -d ${moduledir}/puppet.d/modules/public ] && err 1 "No such ${moduledir}/puppet.d/modules/public"
+
+	if [ "${emulator}" = "jail" ]; then
+		[ $baserw -eq 1 ] && path="${data}"
+		[ -z "${path}" ] && err 1 "No path variable"
+		[ ! -d "${path}/usr/local/etc/puppet/modules" ] && /bin/mkdir -p ${path}/usr/local/etc/puppet/modules
+		[ ! -d ${path}/usr/local/etc/puppet ] && /bin/mkdir -p ${path}/usr/local/etc/puppet
+		[ ! -d ${path}/usr/local/etc/puppet/modules ] && /bin/mkdir ${path}/usr/local/etc/puppet/modules
+		/bin/cp -a ${moduledir}/puppet.d/hiera.yaml ${path}/usr/local/etc/puppet/hiera.yaml
+
+		# first - mount puppet jail source
+		[ ! -d "${path}/tmp/puppet" ] && mkdir -p ${path}/tmp/puppet
+		/sbin/mount -t nullfs -o ro ${_jpuppet_dir} ${path}/tmp/puppet
+		/sbin/mount -t nullfs -o ro ${moduledir}/puppet.d/modules/public ${path}/usr/local/etc/puppet/modules
+		/sbin/mount -t nullfs -o ro ${moduledir}/puppet.d ${path}/tmp/puppet/etc/puppet
+
+		[ $? -ne 0 ] && err 1 "Error mount ${moduledir}/puppet.d/puppet_root/modules to /usr/local/etc/puppet/modules inside jail"
+
+		[ ! -d ${path}/tmp/cbsd ] && /bin/mkdir -p ${path}/tmp/cbsd
+
+		if [ ! -x ${data}/usr/local/bin/puppet ]; then
+			jexec jname=${jname} env ASSUME_ALWAYS_YES=yes pkg install -y sysutils/puppet4
+		fi
+
+	fi
+
+	generate_manifest > ${local_puppet_manifest_dir}/${module}.pp
+
+	[ "${emulator}" = "jail" ] && /bin/cp -a ${local_puppet_manifest_dir}/${module}.pp ${path}/tmp/cbsd/${helpername}.pp
+
+	if [ -d /usr/local/etc/puppet/environments/production/manifests ]; then
+		echo "Copy manifest to /usr/local/etc/puppet/environments/production/manifests/${host_hostname}.pp"
+		echo "node \"${host_hostname}\" {" > /usr/local/etc/puppet/environments/production/manifests/${host_hostname}.pp
+#		/bin/cp ${local_puppet_manifest_dir}/${module}.pp /usr/local/etc/puppet/environments/production/manifests/${host_hostname}.pp
+		/bin/cat ${local_puppet_manifest_dir}/${module}.pp  >> /usr/local/etc/puppet/environments/production/manifests/${host_hostname}.pp
+		echo "}" >> /usr/local/etc/puppet/environments/production/manifests/${host_hostname}.pp
+	else
+		echo "no /usr/local/etc/puppet/environments/production/manifests, skip for coping manifest"
+	fi
+
+	generate_hieradata > ${local_puppet_hieradata_dir}/${module}.yaml
+	[ "${emulator}" = "jail" ] && /bin/cp -a ${local_puppet_hieradata_dir}/${module}.yaml ${path}/tmp/cbsd/common.yaml
+
+	if [ -d /usr/local/etc/puppet/hieradata/production ]; then
+#		[ ! -d /usr/local/etc/puppet/hieradata/production/${helpername} ] && /bin/mkdir -p /usr/local/etc/puppet/hieradata/production/${helpername}
+		[ ! -d /usr/local/etc/puppet/hieradata/production/node ] && /bin/mkdir -p /usr/local/etc/puppet/hieradata/production/node
+		echo "Copy hiera to /usr/local/etc/puppet/hieradata/production/node/"
+		/bin/cp ${local_puppet_hieradata_dir}/${module}.yaml /usr/local/etc/puppet/hieradata/production/node/${host_hostname}.yaml
+	else
+		echo "no /usr/local/etc/puppet/hieradata/production, skip for coping hiera"
+	fi
+
+#	${ECHO} "${MAGENTA}Puppet in progress: ${GREEN}jexec for /tmp/cbsd/${helpername}.pp${NORMAL}"
+#	echo "jexec jname=${jname} /tmp/puppet/etc/puppet/puppetcbsd /tmp/cbsd/${helpername}.pp"
+
+#	jexec jname=${jname} /tmp/puppet/etc/puppet/puppetcbsd /tmp/cbsd/${helpername}.pp
+##	jexec jname=${jname} /usr/local/bin/puppet apply --hiera_config /usr/local/etc/puppet/hiera.yaml /tmp/cbsd/${helpername}.pp
+
+	certname=$( /usr/local/bin/puppet config print certname )
+
+	case "${emulator}" in
+		jail)
+			apply_in_jail
+			;;
+	esac
 }
 
 local_puppet_dir="${jailsysdir}/${jname}/puppet"
